# git clone https://github.com/paullenoir/eliott_prestashop.git
# chmod +x .backups/custom-scripts/restore_volumes.sh
# .backups/custom-scripts/restore_volumes.sh
# docker-compose up -d

version: '3.9'

services:
  mysql:
    image: mysql:8.0
    container_name: prestashop-db
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: prestashop #prestashop
      MYSQL_ROOT_PASSWORD: prestashop #prestashop
    ports:
      - 3306:3306
    networks:
      - prestashop
    volumes:
      - db_data:/var/lib/mysql
      - db_logs:/var/log/mysql

  prestashop:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: prestashop
    environment:
      # DB_SERVER: mysql
      DB_SERVER: mysql
    ports:
      - 8080:80
    networks:
      - prestashop
    volumes:
      - ps_data:/var/www/html
      - ps_themes:/var/www/html/themes
      - ps_modules:/var/www/html/modules
      - ps_img:/var/www/html/img
      - ps_download:/var/www/html/download
      - ps_config:/var/www/html/config
      - ps_override:/var/www/html/override
      - ps_var:/var/www/html/var
    depends_on:
      - mysql

networks:
  prestashop:

volumes:
  db_data:
  db_logs:
  ps_data:
  ps_themes:
  ps_modules:
  ps_img:
  ps_download:
  ps_config:
  ps_override:
  ps_var: