# # boot volume
# # D'abord créer un système de fichiers dessus (si ce n'est pas déjà fait) :
# # sudo mkfs.ext4 /dev/sda1
# # Puis créer un point de montage (un répertoire où le disque sera accessible) :
# # sudo mkdir /mnt/mondisque
# # Enfin, monter le disque sur ce point de montage :
# # sudo mount /dev/sda1 /mnt/mondisque
# # Après ces étapes, vous pourrez faire :
# # cd /mnt/mondisque
# # Installation de PHP et des extensions courantes
# # Ajouter le dépôt PHP
# # sudo apt install software-properties-common
# # sudo add-apt-repository ppa:ondrej/php
# # sudo apt update

# # # Maintenant on peut installer PHP 8.1 et ses extensions
# # sudo apt install -y php8.1 \
# #     php8.1-cli \
# #     php8.1-common \
# #     php8.1-curl \
# #     php8.1-gd \
# #     php8.1-intl \
# #     php8.1-mbstring \
# #     php8.1-mysql \
# #     php8.1-xml \
# #     php8.1-zip \
# #     php8.1-bcmath \
# #     php8.1-fpm

# # # Vérifier la version de PHP installée
# # php -v

# lsblk -o NAME,SIZE,FSTYPE,MOUNTPOINT
# df -h /home/ubuntu

# # Installation de Composer (gestionnaire de dépendances PHP)
# curl -sS https://getcomposer.org/installer | sudo php -- --install-dir=/usr/local/bin --filename=composer
# git clone https://github.com/paullenoir/eliott_prestashop.git
# chmod +x .backups/custom-scripts/restore_volumes.sh
# .backups/custom-scripts/restore_volumes.sh
# docker-compose up -d
# docker-compose logs -f

version: '3.9'

services:
  mysql:
    image: mysql:5.7
    container_name: prestashop-db
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: prestashop #prestashop
      MYSQL_ROOT_PASSWORD: prestashop #prestashop
    ports:
      - 3307:3306
    networks:
      - prestashop
    volumes:
      - db_data:/var/lib/mysql
      - db_logs:/var/log/mysql

  prestashop:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: prestashop
    environment:
      DB_SERVER: mysql
      # DB_NAME: prestashop
      # DB_USER: root
      # DB_PASSWD: prestashop
      # PS_DOMAIN: 204.216.106.138:80
      # PS_INSTALL_AUTO: 1
      # PS_LANGUAGE: fr
      # PS_COUNTRY: FR
      # PS_LOCALE: fr-FR
      # PS_ALL_LANGUAGES: 0
      # PS_FOLDER_ADMIN: admin-dev
      # PS_FOLDER_INSTALL: install
      # ADMIN_MAIL: lenoirpaul76@gmail.com
      # ADMIN_PASSWD: Bonjour3030!
    ports:
      - 8080:80
    networks:
      - prestashop
    volumes:
      - ps_data:/var/www/html
      - ps_themes:/var/www/html/themes
      - ps_modules:/var/www/html/modules
      - ps_img:/var/www/html/img
      - ps_download:/var/www/html/download
      - ps_config:/var/www/html/config
      - ps_override:/var/www/html/override
      - ps_var:/var/www/html/var
    depends_on:
      - mysql

networks:
  prestashop:

volumes:
  db_data:
  db_logs:
  ps_data:
  ps_themes:
  ps_modules:
  ps_img:
  ps_download:
  ps_config:
  ps_override:
  ps_var: